<?php
// app()->importModel("Round2");
$str = '<select name="country" class="country">
    <option selected="selected">--Select Country--</option>
    <option value="1">Afghanistan</option>
<option value="2"> Aland Islands</option>
<option value="3"> Albania</option>
<option value="4"> Algeria</option>
<option value="5"> American Samoa</option>
<option value="6"> Andorra</option>
<option value="7"> Angola</option>
<option value="8"> Anguilla</option>
<option value="9"> Antarctica</option>
<option value="10"> Antigua and Barbuda</option>
<option value="11"> Argentina</option>
<option value="12"> Armenia</option>
<option value="13"> Aruba</option>
<option value="14"> Australia</option>
<option value="15"> Austria</option>
<option value="16"> Azerbaijan</option>
<option value="17"> Bahamas</option>
<option value="18"> Bahrain</option>
<option value="19"> Bangladesh</option>
<option value="20"> Barbados</option>
<option value="21"> Belarus</option>
<option value="22"> Belgium</option>
<option value="23"> Belize</option>
<option value="24"> Benin</option>
<option value="25"> Bermuda</option>
<option value="26"> Bhutan</option>
<option value="27"> Bolivia</option>
<option value="28"> Bosnia and Herzegovina</option>
<option value="29"> Botswana</option>
<option value="30"> Bouvet Island</option>
<option value="31"> Brazil</option>
<option value="32"> British Indian Ocean Territory</option>
<option value="33"> Brunei</option>
<option value="34"> Bulgaria</option>
<option value="35"> Burkina Faso</option>
<option value="36"> Burundi</option>
<option value="37"> Cambodia</option>
<option value="38"> Cameroon</option>
<option value="39"> Canada</option>
<option value="40"> Cape Verde</option>
<option value="41"> Caribbean Netherlands</option>
<option value="42"> Cayman Islands</option>
<option value="43"> Central African Republic</option>
<option value="44"> Chad</option>
<option value="45"> Chile</option>
<option value="46"> China</option>
<option value="47"> Christmas Island</option>
<option value="48"> Cocos (Keeling) Islands</option>
<option value="49"> Colombia</option>
<option value="50"> Comoros</option>
<option value="51"> Congo</option>
<option value="52"> Congo Democratic Republic</option>
<option value="53"> Cook Islands</option>
<option value="54"> Costa Rica</option>
<option value="55">Cote d\'Ivoire</option>
<option value="56"> Croatia</option>
<option value="57"> Cuba</option>
<option value="58"> Curacao</option>
<option value="59"> Cyberbunker</option>
<option value="60"> Cyprus</option>
<option value="61"> Czech Republic</option>
<option value="62"> Denmark</option>
<option value="63"> Djibouti</option>
<option value="64"> Dominica</option>
<option value="65"> Dominican Republic</option>
<option value="66"> East Timor</option>
<option value="67"> Ecuador</option>
<option value="68"> Egypt</option>
<option value="69"> El Salvador</option>
<option value="70"> Equatorial Guinea</option>
<option value="71"> Eritrea</option>
<option value="72"> Estonia</option>
<option value="73"> Ethiopia</option>
<option value="74"> European Union</option>
<option value="75"> Falkland Islands</option>
<option value="76"> Faroe Islands</option>
<option value="77"> Fiji Islands</option>
<option value="78"> Finland</option>
<option value="79"> France</option>
<option value="80"> French Guiana</option>
<option value="81"> French Polynesia</option>
<option value="82"> French Southern territories</option>
<option value="83"> Gabon</option>
<option value="84"> Gambia</option>
<option value="85"> Georgia</option>
<option value="86"> Germany</option>
<option value="87"> Ghana</option>
<option value="88"> Gibraltar</option>
<option value="89"> Greece</option>
<option value="90"> Greenland</option>
<option value="91"> Grenada</option>
<option value="92"> Guadeloupe</option>
<option value="93"> Guam</option>
<option value="94"> Guatemala</option>
<option value="95"> Guernsey</option>
<option value="96"> Guinea</option>
<option value="97"> Guinea-Bissau</option>
<option value="98"> Guyana</option>
<option value="99"> Haiti</option>
<option value="100"> Heard Island and McDonald</option>
<option value="101"> Honduras</option>
<option value="102"> Hong Kong</option>
<option value="103"> Hungary</option>
<option value="104"> Iceland</option>
<option value="105"> India</option>
<option value="106"> Indonesia</option>
<option value="107"> Iran</option>
<option value="108"> Iraq</option>
<option value="109"> Ireland</option>
<option value="110"> Isle of Man</option>
<option value="111"> Israel</option>
<option value="112"> Italy</option>
<option value="113"> Jamaica</option>
<option value="114"> Japan</option>
<option value="115"> Jersey</option>
<option value="116"> Jordan</option>
<option value="117"> Kazakstan</option>
<option value="118"> Kenya</option>
<option value="119"> Kiribati</option>
<option value="120"> Kuwait</option>
<option value="121"> Kyrgyzstan</option>
<option value="122"> Laos</option>
<option value="123"> Latvia</option>
<option value="124"> Lebanon</option>
<option value="125"> Lesotho</option>
<option value="126"> Liberia</option>
<option value="127"> Libya</option>
<option value="128"> Liechtenstein</option>
<option value="129"> Lithuania</option>
<option value="130"> Luxembourg</option>
<option value="131"> Macao</option>
<option value="132"> Macedonia</option>
<option value="133"> Madagascar</option>
<option value="134"> Malawi</option>
<option value="135"> Malaysia</option>
<option value="136"> Maldives</option>
<option value="137"> Mali</option>
<option value="138"> Malta</option>
<option value="139"> Marshall Islands</option>
<option value="140"> Martinique</option>
<option value="141"> Mauritania</option>
<option value="142"> Mauritius</option>
<option value="143"> Mayotte</option>
<option value="144"> Mexico</option>
<option value="145"> Micronesia Federated States</option>
<option value="146"> Moldova</option>
<option value="147"> Monaco</option>
<option value="148"> Mongolia</option>
<option value="149"> Montenegro</option>
<option value="150"> Montserrat</option>
<option value="151"> Morocco</option>
<option value="152"> Mozambique</option>
<option value="153"> Myanmar</option>
<option value="154"> Namibia</option>
<option value="155"> Nauru</option>
<option value="156"> Nepal</option>
<option value="157"> Netherlands</option>
<option value="158"> Netherlands Antilles</option>
<option value="159"> New Caledonia</option>
<option value="160"> New Zealand</option>
<option value="161"> Nicaragua</option>
<option value="162"> Niger</option>
<option value="163"> Nigeria</option>
<option value="164"> Niue</option>
<option value="165"> Norfolk Island</option>
<option value="166"> North Korea</option>
<option value="167"> Northern Mariana Islands</option>
<option value="168"> Norway</option>
<option value="169"> Oman</option>
<option value="170"> Pakistan</option>
<option value="171"> Palau</option>
<option value="172"> Palestine</option>
<option value="173"> Panama</option>
<option value="174"> Papua New Guinea</option>
<option value="175"> Paraguay</option>
<option value="176"> Peru</option>
<option value="177"> Philippines</option>
<option value="178"> Pitcairn</option>
<option value="179"> Poland</option>
<option value="180"> Portugal</option>
<option value="181"> Puerto Rico</option>
<option value="182"> Qatar</option>
<option value="183">Reunion</option>
<option value="184"> Romania</option>
<option value="185"> Russia</option>
<option value="186"> Rwanda</option>
<option value="187"> Saint Barthelemy</option>
<option value="188"> Saint Helena</option>
<option value="189"> Saint Kitts and Nevis</option>
<option value="190"> Saint Lucia</option>
<option value="191"> Saint Martin</option>
<option value="192"> Saint Pierre and Miquelon</option>
<option value="193"> Saint Vincent and the Grenadines</option>
<option value="194"> Samoa</option>
<option value="195"> San Marino</option>
<option value="196"> Sao Tome and Principe</option>
<option value="197"> Saudi Arabia</option>
<option value="198"> Senegal</option>
<option value="199"> Serbia</option>
<option value="200"> Seychelles</option>
<option value="201"> Sierra Leone</option>
<option value="202"> Singapore</option>
<option value="203"> Sint Maarten</option>
<option value="204"> Slovakia</option>
<option value="205"> Slovenia</option>
<option value="206"> Solomon Islands</option>
<option value="207"> Somalia</option>
<option value="208"> South Africa</option>
<option value="209">South Georgia and the South Sandwich Islands</option>
<option value="210"> South Korea</option>
<option value="211"> South Sudan</option>
<option value="212"> Spain</option>
<option value="213"> Sri Lanka</option>
<option value="214"> Sudan</option>
<option value="215"> Suriname</option>
<option value="216"> Svalbard and Jan Mayen</option>
<option value="217"> Swaziland</option>
<option value="218"> Sweden</option>
<option value="219"> Switzerland</option>
<option value="220"> Syria</option>
<option value="221"> Taiwan</option>
<option value="222"> Tajikistan</option>
<option value="223"> Tanzania</option>
<option value="224"> Thailand</option>
<option value="225"> Togo</option>
<option value="226"> Tokelau</option>
<option value="227"> Tonga</option>
<option value="228"> Trinidad and Tobago</option>
<option value="229"> Tunisia</option>
<option value="230"> Turkey</option>
<option value="231"> Turkmenistan</option>
<option value="232"> Turks and Caicos Islands</option>
<option value="233"> Tuvalu</option>
<option value="234"> Uganda</option>
<option value="235"> Ukraine</option>
<option value="236"> United Arab Emirates</option>
<option value="237"> United Kingdom</option>
<option value="238"> United States Minor Outlying</option>
<option value="239"> Uruguay</option>
<option value="240"> USA</option>
<option value="241"> Uzbekistan</option>
<option value="242"> Vanuatu</option>
<option value="243"> Vatican (Holy See)</option>
<option value="244"> Venezuela</option>
<option value="245"> Vietnam</option>
<option value="246"> Virgin Islands British</option>
<option value="247"> Virgin Islands U.S.</option>
<option value="248"> Wallis and Futuna</option>
<option value="249"> Western Sahara</option>
<option value="250"> Yemen</option>
<option value="251"> Zambia</option>
<option value="252"> Zimbabwe</option>  </select>';

$parser = app()->helper("Parser");

$result = $parser->parseDropdown($str);

$app = app();
// create tmp dirs for each country
foreach ($result as $country) {
    $app->prepareDir($country['text']);
}

// Save index files
file_put_contents(TMP_DIR . "/index.txt", serialize($result));

$output = array(
    "total" => count($result),
    "items" => $result
);
header("Content-type: application/json");

echo json_encode($output);